### ISSUE TITLE
Z endtop

### ISSUE THREAD

**Issue by timmit99** [mjrice/Wilson2#8]
I noticed that the X-Motor has the adjustable screw for  the Z endstop but i don't see a Z endstop.stl. Is it the same as the Wilson V1 mount?

**Comment by mjrice** [comment]
wilson2 is meant to use the servo-mounted endstop by default, so it doesn't need that one.  I didn't want to get rid of the adjustment screw mount on the X end however in case people want to use that instead of the servo for simplicity.  In that case, yes you'd just use the same endstop holder from wilson.
